# vim: ft=kitty

# Guts-Whisper — OKLCH chroma ×1.20 over guts base

foreground            #9f9e91
background            #101113
cursor                #9f9e91
cursor_text_color     #101113
selection_foreground  #e1ffda
selection_background  #564961

# black / bright black
color0  #161719
color8  #564961

# red / bright red
color1  #76271f
color9  #76271f

# green / bright green
color2  #798475
color10 #9fdba1

# yellow / bright yellow
color3  #b27c71
color11 #b27c71

# blue / bright blue
color4  #667a9a
color12 #81889e

# magenta / bright magenta
color5  #914a4b
color13 #9c7c91

# cyan / bright cyan
color6  #81889e
color14 #9fdba1

# white / bright white
color7  #9f9e91
color15 #9fdba1
