# vim: ft=kitty

# Guts-Scream — OKLCH chroma ×1.45 over guts base

foreground            #a09e8f
background            #101113
cursor                #a09e8f
cursor_text_color     #101113
selection_foreground  #e1ffda
selection_background  #584766

# black / bright black
color0  #161719
color8  #584766

# red / bright red
color1  #7e1a16
color9  #7e1a16

# green / bright green
color2  #778474
color10 #95de9a

# yellow / bright yellow
color3  #b9786d
color11 #b9786d

# blue / bright blue
color4  #617aa2
color12 #7f87a3

# magenta / bright magenta
color5  #994347
color13 #a07994

# cyan / bright cyan
color6  #7f87a3
color14 #95de9a

# white / bright white
color7  #a09e8f
color15 #95de9a
