# vim: ft=kitty

# Guts — dark Berserk-inspired colorscheme

foreground            #9f9e99
background            #101113
cursor                #9f9e99
cursor_text_color     #101113
selection_foreground  #e1ffe5
selection_background  #554A62

# black / bright black
color0  #161719
color8  #554A62

# red / bright red
color1  #6f2e2a
color9  #6f2e2a

# green / bright green
color2  #7a837c
color10 #a7d8b0

# yellow / bright yellow
color3  #ac7f7b
color11 #ac7f7b

# blue / bright blue
color4  #697a9a
color12 #8288A0

# magenta / bright magenta
color5  #8a4f53
color13 #997e95

# cyan / bright cyan
color6  #8288A0
color14 #a7d8b0

# white / bright white
color7  #9f9e99
color15 #a7d8b0
